### ISSUE TITLE
Add snapcraft.yaml from Snappy Playpen

### ISSUE THREAD

**Issue by dholbach** [stolowski/QComicBook#20]
Hello,

it'd be great if https://github.com/ubuntu/snappy-playpen/tree/master/qcomicbook could be added to QComicBook. It'd be good to change
```yaml
source: https://github.com/stolowski/QComicBook.git
```

to:

```yaml
source: .
```

Apart from that it should hopefully work. The files in `./setup/gui` could probably be symlinks.

**Comment by stolowski** [comment]
Thanks for reminding me, added!
