### ISSUE TITLE
[request] Qt5 port

### ISSUE THREAD

**Issue by ahjolinna** [stolowski/QComicBook#6]
As the title suggest could you port this app to Qt5? or is this a dead project?

**Comment by greydot** [comment]
@ahjolinna https://github.com/greydot/QComicBook

**Comment by heroin-moose** [comment]
If Qt5-code is usable maybe it's time for another minor release then? I will be happy to bump a package in Gentoo since qcomicbook is the only qt4 app left on my laptop.

**Comment by stolowski** [comment]
0.9.1 including Qt5 support by greydot has been released.
